const { defineConfig } = require('eslint/config');
const js = require('@eslint/js');
const expo = require('eslint-config-expo/flat');
const { FlatCompat } = require('@eslint/eslintrc');

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

// Uniwind cannot cssInterop third-party components, so SafeAreaView is banned
// with no exceptions — it rides along in every block below, overrides included.
const safeAreaRestriction = {
  name: 'react-native-safe-area-context',
  importNames: ['SafeAreaView'],
  message: "Uniwind cannot style third-party components — use <View className='pt-safe'> (see DESIGN.md).",
};

// Vendor SDKs may only be imported by the file that owns them; everywhere else
// app code goes through the neutral seam named in the message.
const restrictedImports = () => [
  'error',
  { paths: [safeAreaRestriction] },
];


module.exports = defineConfig([
  js.configs.recommended,

  ...expo,

  ...compat.extends('prettier'),

  {
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        {
          prefer: 'type-imports',
          fixStyle: 'inline-type-imports',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'max-lines': ['warn', { max: 250, skipBlankLines: true, skipComments: true }],
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-misused-promises': [
        'error',
        {
          checksVoidReturn: false,
        },
      ],
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-var-requires': 'off',
    },
  },

  {
    files: ['src/**/*.{ts,tsx,js,jsx}'],
    rules: {
      'no-restricted-imports': restrictedImports(),
      'no-restricted-properties': [
        'error',
        {
          object: 'Intl',
          property: 'RelativeTimeFormat',
          message:
            'Not shipped by Hermes — crashes at runtime. Use relativeTime() from src/lib/format/relativeTime.ts.',
        },
      ],
    },
  },

  // The edge functions are Deno and excluded from tsconfig.json, so every
  // type-aware rule is off here; the syntax-level ones still apply.
  {
    files: ['supabase/functions/**/*.ts'],
    languageOptions: {
      parserOptions: { project: null, projectService: false },
    },
    rules: {
      '@typescript-eslint/no-misused-promises': 'off',
      'import/no-unresolved': 'off',
    },
  },

  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/*.config.js',
      '**/config.js',
      '**/eslint.config.js',
      '**/src/lib/db/database.types.ts', // generated by `supabase gen types` — never hand-edited
    ],
  },
]);
